library(ngram)
library(shiny)
library(dplyr)
library(quanteda)
library(tidytext)
library(wordcloud)
library(ggplot2)
library(ngram)
library(topicmodels)
load("data/lda_app.RData")
load("data/naive_bayes.RData")
source("ui.R")
source("server.R")
#Shiny App for Word Cloud,tf-idf dynamic
shinyApp(ui, server)
